<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class ArticleResource extends JsonResource
{
    public function toArray(Request $request): array
    {
        return [
            'id' => $this->id,
            'title' => $this->title,
            'excerpt' => $this->excerpt,
            'content' => $this->content,
            'category' => $this->category,
            'image_url' => $this->image_url,
            'image_author' => $this->image_author,
            'author' => $this->author,
            'author_user_id' => $this->author_user_id,
            'coauthor' => $this->coauthor,
            'coauthor_user_id' => $this->coauthor_user_id,
            'published_at' => $this->published_at,
            'featured' => $this->featured,
            'is_patronage' => $this->is_patronage,
            'tags' => $this->tags,
            'hide_in_reels' => $this->hide_in_reels,
            'skip_homepage' => $this->skip_homepage,
            'likes' => $this->likes,
            'person_name' => $this->person_name,
            'bydgoszczanie' => $this->bydgoszczanie,
            'source_name' => $this->source_name,
            'source_url' => $this->source_url,
            'expert_quote' => $this->expert_quote,
            'slug' => $this->slug,
            'label_urgent' => $this->label_urgent,
            'label_important' => $this->label_important,
            'label_our_news' => $this->label_our_news,
            'label_must_know' => $this->label_must_know,
            'label_author_article' => $this->label_author_article,
            'label_18_plus' => $this->label_18_plus,
            'label_depresja' => $this->label_depresja,
            'bibliography' => $this->bibliography,
            'sources' => $this->sources,
            'footer_info' => $this->footer_info,
            'source_from_contact' => $this->source_from_contact,
            'article_type' => $this->article_type,
            'article_template' => $this->article_template,
            'status' => $this->status,
            'scheduled_at' => $this->scheduled_at,
            'layout' => $this->layout,
            'partner_name' => $this->partner_name,
            'partner_url' => $this->partner_url,
            'partner_logo_url' => $this->partner_logo_url,
            'partner_label' => $this->partner_label,
            'seo_title' => $this->seo_title,
            'seo_description' => $this->seo_description,
            'allow_comments' => $this->allow_comments,
            'show_updates' => $this->show_updates,
            'graphics_layout' => $this->graphics_layout,
            'category_layout' => $this->category_layout,
            'article_elements' => $this->article_elements,
            'coauthor2' => $this->coauthor2,
            'coauthor3' => $this->coauthor3,
            'corrector' => $this->corrector,
            'publisher' => $this->publisher,
            'author_footer_style' => $this->author_footer_style,
            'poll' => $this->poll,
            'quiz' => $this->quiz,
            'interview' => $this->interview,
            'analysis' => $this->analysis,
            'report' => $this->report,
            'opinion' => $this->opinion,
            'dialog' => $this->dialog,
            'announcement' => $this->announcement,
            'sponsored' => $this->sponsored,
            'sport' => $this->sport,
            'politics' => $this->politics,
            'investment' => $this->investment,
            'our_actions' => $this->our_actions,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
        ];
    }
}
